Repository AY2122S2-CS2103T-W09-2/tp, pull requests merged in 2022-03, with the labels that each got.

#27 Slight update to documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#28 More changes to ReadMe and user guide.
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#35 Add command chaining
  docs/UserGuide.md
  docs/team/danemarc.md
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Task

#43 Update containsWordIgnoreCase method to allow partial matches
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Enhancement

#44 [Resolves #41] Make saving system modular.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Field.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/SerializableAddressBookStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Story, priority.High, severity.High

#37 Add Membership functionality
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddMembershipCommand.java
  src/main/java/seedu/address/logic/commands/CommandRegistry.java
  src/main/java/seedu/address/logic/commands/DeleteFilteredCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMembershipParser.java
  src/main/java/seedu/address/model/person/Membership.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/DeleteFilteredCommandTest.java
Labels: type.Story, priority.Medium

#46 Update the test cases so that they better reflect the current state of t…
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IndexParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/JsonSerializableTestClass.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High, severity.High

#58 Create test cases for sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Field.java
  src/main/java/seedu/address/model/person/Membership.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/testutil/SortUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#62 Add panel for Transaction list
  src/main/java/seedu/address/model/transaction/DueDate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/java/seedu/address/ui/TransactionListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
Labels: type.Task

#64 Transaction enhancement
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/CommandRegistry.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/logic/parser/ListTransactionCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/transaction/DueDate.java
  src/main/java/seedu/address/model/transaction/Note.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionDate.java
  src/main/java/seedu/address/model/transaction/TransactionFieldRegistry.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, type.Enhancement, type.Bug

#68 fix bug - invalid birthday date
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.High

#67 Implement Transaction Card
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListTransactionCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/DueDate.java
  src/main/java/seedu/address/model/transaction/Note.java
  src/main/java/seedu/address/model/transaction/TransactionDate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: type.Task

#72 Update UI
  src/main/resources/view/Cinnamon.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: type.Enhancement

#79 Update DG for Transaction Implementation
  docs/DeveloperGuide.md
  docs/team/zunedz.md
Labels: type.Task

#78 Add Tests for Transaction
  src/main/java/seedu/address/model/transaction/DueDate.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionDate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/transaction/AmountTest.java
  src/test/java/seedu/address/model/transaction/DueDateTest.java
  src/test/java/seedu/address/model/transaction/NoteTest.java
  src/test/java/seedu/address/model/transaction/TransactionDateTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
Labels: type.Task

#81 Update developer guide for sortCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, documentation

#82 Update DG, add asserts, and minor UI tweaks
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/Cinnamon.css
Labels: type.Enhancement, documentation

#80 Undo command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandRegistry.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/SerializableTempAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TempAddressBookStorage.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Story

#86 Add command history
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Story, priority.High

#89 Update preferences.json
  .gitignore
  preferences.json
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: type.Task, priority.High

#91 Add unique id to Person for transactions to reference
  .gitignore
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, priority.High, severity.High

#96 Fix autocomplete/autocorrect edge cases
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug

#100 List transaction on personCard click
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Enhancement

#107 Add RemarkCommand to user guide
  docs/UserGuide.md
Labels: documentation

#110 Update UI
  docs/images/Ui.png
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/Cinnamon.css
  src/main/resources/view/MainWindow.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TransactionListCard.fxml
Labels: type.Enhancement

#111 Add GUI Overview to UserGuide.md
  docs/UserGuide.md
  docs/images/GuiOverview.png
Labels: documentation

#114 Update README
  README.md
  docs/_config.yml
Labels: documentation

#113 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#121 Update click to view transactions to handle deselection
  src/main/java/seedu/address/model/person/util/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/Caramel.css
  src/main/resources/view/Cinnamon.css
  src/main/resources/view/MainWindow.css
Labels: type.Enhancement

#122 Add Status attribute to the transaction
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/transaction/Note.java
  src/main/java/seedu/address/model/transaction/Status.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionFieldRegistry.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/TransactionListCard.fxml
Labels: type.Task

#125 Add pay and unpay command
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/CommandRegistry.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/commands/UnpayCommand.java
  src/main/java/seedu/address/logic/parser/PayCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpayCommandParser.java
  src/main/java/seedu/address/model/transaction/DueDate.java
  src/main/java/seedu/address/model/transaction/Status.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/transaction/TransactionDate.java
  src/main/java/seedu/address/model/transaction/util/DateFieldInterface.java
  src/main/java/seedu/address/model/transaction/util/StatusFactory.java
Labels: type.Story

#127 Membership now uses tiers instead of names, ListMembers functionality added
  src/main/java/seedu/address/logic/commands/AddMembershipCommand.java
  src/main/java/seedu/address/logic/commands/CommandRegistry.java
  src/main/java/seedu/address/logic/commands/ListMembersCommand.java
  src/main/java/seedu/address/logic/parser/ListMembersCommandParser.java
  src/main/java/seedu/address/model/person/Membership.java
  src/main/java/seedu/address/model/person/util/PersonContainsMembershipPredicate.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/Caramel.css
  src/main/resources/view/Cinnamon.css
  src/test/java/seedu/address/logic/commands/AddMembershipCommandTest.java
  src/test/java/seedu/address/logic/parser/AddMembershipParserTest.java
  src/test/java/seedu/address/model/person/MembershipTest.java
Labels: type.Enhancement

#132 Update membership ui
  src/main/resources/view/Caramel.css
  src/main/resources/view/Cinnamon.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#136 Update command completion/correction to prioritize completion
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement

#138 Add test case for AddTransaction
  src/main/java/seedu/address/logic/commands/AddTransactionCommand.java
  src/main/java/seedu/address/logic/commands/FindTransactionCommand.java
  src/main/java/seedu/address/logic/parser/AddTransactionParser.java
  src/main/java/seedu/address/model/transaction/DueDate.java
  src/main/java/seedu/address/model/transaction/TransactionDate.java
  src/main/java/seedu/address/model/transaction/util/TransactionBuilder.java
  src/main/java/seedu/address/model/transaction/util/TransactionPredicateBuilder.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTransactionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
Labels: type.Task, priority.Medium

#139 Created test cases for undo command and temporary file saving
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/storage/SerializableTempAddressBookStorage.java
  src/test/data/TempAddressBookStorageTest/invalidTempAddressbookTest.json
  src/test/data/TempAddressBookStorageTest/validTempAddressbookTest.json
  src/test/java/seedu/address/logic/LogicManagerIntegrationTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/storage/SerializableTempAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.High, severity.Medium

#144 Add test cases for transaction commands
  src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/commands/FindTransactionCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/commands/UnpayCommand.java
  src/main/java/seedu/address/logic/parser/PayCommandParser.java
  src/main/java/seedu/address/logic/parser/UnpayCommandParser.java
  src/main/java/seedu/address/model/transaction/Status.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/test/java/seedu/address/logic/commands/AddTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTransactionCommandTest.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
  src/test/java/seedu/address/logic/commands/UnpayCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTransactionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTransactionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PayCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnpayCommandParserTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: type.Task, priority.Medium

#154 Update LogicManager and find
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/person/util/PersonContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Enhancement

#157 Update user guide on INDEX
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/commands/AddMembershipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTransactionCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindTransactionCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/RemoveMembershipCommand.java
  src/main/java/seedu/address/logic/commands/UnpayCommand.java
Labels: type.Bug, priority.High, severity.VeryLow, documentation
