Repository AY2122S2-CS2103T-W09-2/tp, pull requests merged in 2022-04, with the labels that each got.

#206 Fixes cut off text in boxes
  src/main/resources/view/MainWindow.css
Labels: type.Bug

#213 Fix userguide to address issue #184 and other possible issues
  docs/UserGuide.md
Labels: type.Bug, documentation

#214 Fix Reposense claim
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/storage/SerializableTempAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TempAddressBookStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Task, priority.Medium

#216 Update PPP, closes issue #187, #189, #193, #194, #195, #196, #198
  docs/UserGuide.md
  docs/team/typedefinition.md
Labels: documentation

#219 Update UG for sort command
  docs/UserGuide.md
Labels: documentation

#220 Update PPP
  docs/team/danemarc.md
Labels: documentation

#221 update PPP
  docs/team/zunedz.md
Labels: documentation

#230 Update UserGuide, PPP and gave credit for reused code
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/danemarc.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: documentation

#232 Update PPP, DG with membership functionality and fixed typo in listMe…
  docs/DeveloperGuide.md
  docs/team/keithczw.md
  src/main/java/seedu/address/logic/commands/ListMembersCommand.java
Labels: documentation

#236 Fix typos in DG
  docs/DeveloperGuide.md
Labels: documentation

#243 Fix reposense claim
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: documentation

#247 Proof read Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ParserClasses.puml
  docs/images/ParserClasses.png
Labels: documentation
